services:
  mongodb:
    image: mongo:8
    restart: on-failure
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    ports:
      - "27017:27017"

  dp-ingestion:
    image: ghcr.io/slaclab/dp-service:v1.13
    container_name: dp-ingestion
    depends_on:
      - mongodb
    entrypoint:
      - "java"
    environment:
      - DP_MONGO_DB_URI=mongodb://admin:admin@mongodb:27017/dp?authSource=admin
    command:
      - "-cp"
      - "/app/app.jar"
      - "com.ospreydcs.dp.service.ingest.server.IngestionGrpcServer"
    ports:
      - "50051:50051"
  
  dp-query:
    image: ghcr.io/slaclab/dp-service:v1.13
    container_name: dp-query
    depends_on:
      - mongodb
    entrypoint:
      - "java"
    environment:
      - DP_MONGO_DB_URI=mongodb://admin:admin@mongodb:27017/dp?authSource=admin
    command:
        - "-Ddp.MongoClient.dbHost=mongodb"
        - "-Ddp.MongoClient.dbPort=27017"
        - "-Ddp.MongoClient.dbUser=admin"
        - "-Ddp.MongoClient.dbPassword=admin"
        - "-Ddp.GrpcClient.hostname=dp-ingestion"
        - "-Ddp.IngestionServer.port=50052"
        - "-cp"
        - "/app/app.jar"
        - "com.ospreydcs.dp.service.query.server.QueryGrpcServer"
    ports:
      - "50052:50052"
      
volumes:
  kafka-data:
