apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mldp-pvxs

resources:
  - namespace.yaml
  - configmap.yaml
  # - secret-tls.yaml
  - deployment.yaml

# Override image tag per environment:
#   kustomize edit set image ghcr.io/slaclab/mldp-pvxs-driver=ghcr.io/slaclab/mldp-pvxs-driver:v0.2.5
images:
  - name: ghcr.io/slaclab/mldp-pvxs-driver
    newTag: latest
