//////////////////////////////////////////////////////////////////////////////
// This file is part of 'mldp-pvxs-driver'.
// It is subject to the license terms in the LICENSE.txt file found in the
// top-level directory of this distribution and at:
//    https://confluence.slac.stanford.edu/display/ppareg/LICENSE.html.
// No part of 'mldp-pvxs-driver', including this file,
// may be copied, modified, propagated, or distributed except according to
// the terms contained in the LICENSE.txt file.
//////////////////////////////////////////////////////////////////////////////

#include <query/parser/QueryParser.h>

#include <query/parser/Lexer.h>
#include <query/parser/generated/QueryBisonContext.h>
#include <query/parser/generated/QueryBisonParser.hpp>

#include <algorithm>
#include <cctype>
#include <charconv>
#include <optional>
#include <unordered_map>
using namespace mldp_pvxs_driver::query;

QueryParser::QueryParser(std::vector<Token> tokens)
    : tokens_(std::move(tokens))
{
}

QueryStatement QueryParser::parse()
{
    generated::ParseContext context{
        .tokens = tokens_,
        .index = 0,
        .result = QueryStatement{}};
    generated::QueryBisonParser parser(context);
    if (parser.parse() != 0)
    {
        const auto position = context.has_last_position
            ? context.last_position
            : TokenPosition{0, 1, 1};
        throw ParseError("Failed to parse query", position);
    }
    return context.result;
}

QueryStatement QueryParser::parse(const std::string_view sql)
{
    const auto trim = [](std::string_view value)
    {
        const auto begin = value.find_first_not_of(" \t\r\n");
        const auto end = value.find_last_not_of(" \t\r\n;");
        return begin == std::string_view::npos ? std::string_view{} : value.substr(begin, end - begin + 1);
    };
    const auto uppercase = [](std::string_view value)
    {
        std::string result(value);
        std::transform(result.begin(), result.end(), result.begin(), [](const unsigned char character)
                       { return static_cast<char>(std::toupper(character)); });
        return result;
    };
    std::string text(trim(sql));
    // The checked-in parser is generated by Bison 3.7+.  Keep these two
    // statement-only forms available to source builds until regeneration.
    const auto normalized_statement = uppercase(text);
    if (normalized_statement == "SHOW FUNCTIONS") return ShowFunctionsStatement{};
    if (normalized_statement == "SHOW OPERATORS") return ShowOperatorsStatement{};
    const auto first_token_end = text.find_first_of(" \t\r\n");
    if (uppercase(text.substr(0, first_token_end)) == "DESC")
    {
        text = "DESCRIBE" + std::string(text.substr(first_token_end));
    }
    std::unordered_map<std::string, LiteralValue> typed_literals;
    const auto rewriteTypedLiterals = [&typed_literals](const std::string_view value)
    {
        std::string rewritten;
        rewritten.reserve(value.size());
        bool quoted = false;
        char quote = '\0';
        for (std::size_t index = 0; index < value.size();)
        {
            if (quoted)
            {
                rewritten += value[index];
                if (value[index] == '\\' && index + 1 < value.size()) rewritten += value[++index];
                else if (value[index] == quote) quoted = false;
                ++index;
                continue;
            }
            if (value[index] == '\'' || value[index] == '"')
            {
                quote = value[index];
                quoted = true;
                rewritten += value[index++];
                continue;
            }
            const auto is_identifier = [](const char character)
            {
                return std::isalnum(static_cast<unsigned char>(character)) || character == '_';
            };
            if (!std::isalpha(static_cast<unsigned char>(value[index])) && value[index] != '_')
            {
                rewritten += value[index++];
                continue;
            }
            const auto start = index;
            while (index < value.size() && is_identifier(value[index])) ++index;
            const auto word = value.substr(start, index - start);
            std::string upper(word);
            std::transform(upper.begin(), upper.end(), upper.begin(), [](const unsigned char character) { return static_cast<char>(std::toupper(character)); });
            if ((upper == "TRUE" || upper == "FALSE") && (start == 0 || !is_identifier(value[start - 1])) &&
                (index == value.size() || !is_identifier(value[index])))
            {
                const auto marker = "typed_literal_" + std::to_string(typed_literals.size());
                typed_literals.emplace(marker, LiteralValue{upper == "TRUE"});
                rewritten += "'" + marker + "'";
                continue;
            }
            if (upper != "TIMESTAMP_NS" && upper != "DURATION_NS")
            {
                rewritten.append(word);
                continue;
            }
            auto cursor = index;
            while (cursor < value.size() && std::isspace(static_cast<unsigned char>(value[cursor]))) ++cursor;
            if (cursor == value.size() || value[cursor] != '(')
            {
                rewritten.append(word);
                continue;
            }
            ++cursor;
            while (cursor < value.size() && std::isspace(static_cast<unsigned char>(value[cursor]))) ++cursor;
            const auto number_start = cursor;
            if (cursor < value.size() && value[cursor] == '-') ++cursor;
            const auto digits_start = cursor;
            while (cursor < value.size() && std::isdigit(static_cast<unsigned char>(value[cursor]))) ++cursor;
            const auto number_end = cursor;
            while (cursor < value.size() && std::isspace(static_cast<unsigned char>(value[cursor]))) ++cursor;
            if (digits_start == number_end || cursor == value.size() || value[cursor] != ')')
                throw ParseError("Invalid " + std::string(word) + " literal", TokenPosition{start, 1, start + 1});
            int64_t ns = 0;
            const auto [end, error] = std::from_chars(value.data() + number_start, value.data() + number_end, ns);
            if (error != std::errc{} || end != value.data() + number_end)
                throw ParseError("Invalid " + std::string(word) + " literal", TokenPosition{start, 1, start + 1});
            const auto marker = "typed_literal_" + std::to_string(typed_literals.size());
            typed_literals.emplace(marker, upper == "TIMESTAMP_NS" ? LiteralValue{TimestampNsLiteral{ns}} : LiteralValue{DurationNsLiteral{ns}});
            rewritten += "'" + marker + "'";
            index = cursor + 1;
        }
        return rewritten;
    };
    const auto parseDecimalLiteral = [](const std::string_view value) -> std::optional<double>
    {
        if (value.empty()) return std::nullopt;
        double result = 0;
        const auto [end, error] = std::from_chars(value.data(), value.data() + value.size(), result);
        if (error != std::errc{} || end != value.data() + value.size()) return std::nullopt;
        return result;
    };
    const auto rewriteDecimalLiterals = [&parseDecimalLiteral](const std::string_view value,
                                                                std::unordered_map<std::string, double>& decimals)
    {
        std::string rewritten;
        rewritten.reserve(value.size());
        bool quoted = false;
        char quote = '\0';
        for (std::size_t index = 0; index < value.size();)
        {
            if (quoted)
            {
                rewritten += value[index];
                if (value[index] == '\\' && index + 1 < value.size())
                {
                    rewritten += value[index + 1];
                    index += 2;
                    continue;
                }
                if (value[index++] == quote) quoted = false;
                continue;
            }
            if (value[index] == '\'' || value[index] == '"')
            {
                quote = value[index];
                quoted = true;
                rewritten += value[index++];
                continue;
            }
            const auto previous_non_space = [&value, index]() -> char
            {
                auto previous = index;
                while (previous > 0 && std::isspace(static_cast<unsigned char>(value[previous - 1]))) --previous;
                return previous == 0 ? '\0' : value[previous - 1];
            };
            const auto is_unary_sign = [&previous_non_space, &value, index]()
            {
                if (value[index] != '+' && value[index] != '-') return false;
                const auto previous = previous_non_space();
                return previous == '\0' || previous == '(' || previous == ',' || previous == '=' || previous == '!' ||
                       previous == '<' || previous == '>' || previous == '+' || previous == '-';
            };
            const bool begins_number = std::isdigit(static_cast<unsigned char>(value[index])) ||
                                       (value[index] == '.' && index + 1 < value.size() && std::isdigit(static_cast<unsigned char>(value[index + 1]))) ||
                                       (is_unary_sign() && index + 1 < value.size() &&
                                        (std::isdigit(static_cast<unsigned char>(value[index + 1])) ||
                                         (value[index + 1] == '.' && index + 2 < value.size() && std::isdigit(static_cast<unsigned char>(value[index + 2])))));
            if (!begins_number)
            {
                rewritten += value[index++];
                continue;
            }
            std::size_t end = index;
            while (end < value.size() && (std::isdigit(static_cast<unsigned char>(value[end])) || value[end] == '.' || value[end] == 'e' || value[end] == 'E' ||
                                          ((value[end] == '+' || value[end] == '-') &&
                                           (end == index || (end > index && (value[end - 1] == 'e' || value[end - 1] == 'E'))))))
                ++end;
            const auto candidate = value.substr(index, end - index);
            const auto adjacent_identifier = [&value, index, end]()
            {
                const auto is_identifier_character = [](const char character)
                {
                    return std::isalnum(static_cast<unsigned char>(character)) || character == '_';
                };
                return (index > 0 && is_identifier_character(value[index - 1])) ||
                       (end < value.size() && is_identifier_character(value[end]));
            };
            const auto decimal = parseDecimalLiteral(candidate);
            if (adjacent_identifier() || candidate.find_first_of(".eE") == std::string_view::npos || !decimal)
            {
                rewritten.append(candidate);
                index = end;
                continue;
            }
            const auto marker = "decimal_literal_" + std::to_string(decimals.size());
            decimals.emplace(marker, *decimal);
            rewritten += "'" + marker + "'";
            index = end;
        }
        return rewritten;
    };
    const auto equalsIgnoreCase = [](const std::string_view left, const std::string_view right)
    {
        if (left.size() != right.size()) return false;
        return std::equal(left.begin(), left.end(), right.begin(), [](const char left, const char right)
                          { return std::toupper(static_cast<unsigned char>(left)) == std::toupper(static_cast<unsigned char>(right)); });
    };
    const auto create_header_error = []
    {
        throw ParseError("CREATE TABLE header must be CREATE [TEMP] TABLE <name> AS SELECT ...", TokenPosition{});
    };
    const auto create_tokens = Lexer(text).tokenize();
    const auto is_identifier = [&equalsIgnoreCase, &create_tokens](const std::size_t index, const std::string_view value)
    {
        return index < create_tokens.size() && create_tokens[index].type == TokenType::IDENTIFIER &&
               equalsIgnoreCase(create_tokens[index].lexeme, value);
    };
    if (is_identifier(0, "CREATE"))
    {
        std::size_t index = 1;
        const bool temporary = is_identifier(index, "TEMP");
        if (temporary) ++index;
        if (!is_identifier(index, "TABLE")) create_header_error();
        ++index;

        if (index >= create_tokens.size() || create_tokens[index].type != TokenType::IDENTIFIER) create_header_error();
        std::string table_name = create_tokens[index++].lexeme;
        while (index + 1 < create_tokens.size() && create_tokens[index].type == TokenType::DOT &&
               create_tokens[index + 1].type == TokenType::IDENTIFIER)
        {
            table_name += "." + create_tokens[index + 1].lexeme;
            index += 2;
        }
        if (index >= create_tokens.size() || create_tokens[index].type != TokenType::AS) create_header_error();
        const auto as = create_tokens[index];
        ++index;
        if (index >= create_tokens.size() || create_tokens[index].type == TokenType::END_OF_INPUT)
            throw ParseError("CREATE TABLE requires a SELECT query after AS", as.position);

        for (std::size_t child_index = index; child_index < create_tokens.size(); ++child_index)
        {
            if (create_tokens[child_index].type == TokenType::SELECT) break;
            if (create_tokens[child_index].type == TokenType::AS) create_header_error();
        }

        const auto child = trim(std::string_view(text).substr(as.position.offset + as.lexeme.size()));
        QueryStatement parsed;
        try
        {
            parsed = QueryParser::parse(child);
        }
        catch (const ParseError&)
        {
            throw ParseError("CREATE TABLE requires a SELECT query after AS", as.position);
        }
        if (!std::holds_alternative<SelectStatement>(parsed)) throw ParseError("CREATE TABLE requires a SELECT query after AS", as.position);
        return CreateTableStatement{.table_name = std::move(table_name), .temporary = temporary,
                                    .query = std::get<SelectStatement>(parsed)};
    }
    const auto starts = [&text](const std::string_view prefix)
    {
        if (text.size() < prefix.size()) return false;
        return std::equal(prefix.begin(), prefix.end(), text.begin(), [](const char left, const char right)
                          { return std::toupper(static_cast<unsigned char>(left)) == std::toupper(static_cast<unsigned char>(right)); });
    };
    if (starts("DROP TABLE "))
    {
        const auto name = trim(std::string_view(text).substr(std::string_view{"DROP TABLE "}.size()));
        if (name.empty() || name.find_first_of(" \t\r\n") != std::string_view::npos) throw ParseError("DROP TABLE requires one table name", TokenPosition{});
        return DropTableStatement{.table_name = std::string(name)};
    }

    // The generated grammar deliberately keeps subqueries out of scope.
    // Recognize parenthesized SELECTs in FROM/JOIN and IN positions, parse
    // their bodies recursively, and replace them with private markers for
    // the normal SELECT grammar.
    std::unordered_map<std::string, std::shared_ptr<SelectStatement>> derived;
    std::unordered_map<std::string, std::shared_ptr<SelectStatement>> in_subqueries;
    std::unordered_map<std::string, std::vector<InPredicate::WindowShardOption>> in_subquery_window_options;
    std::unordered_map<std::string, bool> is_not_null;
    std::string rewritten = rewriteTypedLiterals(text);
    std::size_t search = 0;
    unsigned int derived_number = 0;
    while ((search = rewritten.find('(', search)) != std::string::npos)
    {
        const auto before = trim(std::string_view(rewritten).substr(0, search));
        const auto word_start = before.find_last_of(" \t\r\n");
        const auto previous = uppercase(before.substr(word_start == std::string_view::npos ? 0 : word_start + 1));
        if (previous != "FROM" && previous != "JOIN" && previous != "IN")
        {
            ++search;
            continue;
        }
        std::size_t depth = 1;
        std::size_t end = search + 1;
        for (; end < rewritten.size() && depth != 0; ++end)
        {
            if (rewritten[end] == '(') ++depth;
            else if (rewritten[end] == ')') --depth;
        }
        if (depth != 0) throw ParseError("Unclosed subquery", TokenPosition{});
        auto child_sql = trim(std::string_view(rewritten).substr(search + 1, end - search - 2));
        std::vector<InPredicate::WindowShardOption> window_options;
        if (previous == "IN" && uppercase(child_sql).rfind("SELECT", 0) == 0)
        {
            const auto option_separator = child_sql.find(';');
            if (option_separator != std::string_view::npos)
            {
                const auto options_sql = trim(child_sql.substr(option_separator + 1));
                child_sql = trim(child_sql.substr(0, option_separator));
                for (std::size_t offset = 0; offset < options_sql.size();)
                {
                    const auto comma = options_sql.find(',', offset);
                    const auto option = trim(options_sql.substr(offset, comma == std::string_view::npos ? std::string_view::npos : comma - offset));
                    const auto separator = option.find_first_of(" \t\r\n");
                    if (separator == std::string_view::npos) throw ParseError("Window option must have a name and value", TokenPosition{});
                    const auto name = std::string(option.substr(0, separator));
                    const auto value = trim(option.substr(separator + 1));
                    if (name == "slice" || name == "SLICE")
                    {
                        const auto tokens = Lexer(value).tokenize();
                        if (tokens.size() != 2 || tokens.front().type != TokenType::DURATION_LITERAL)
                            throw ParseError("Window slice option requires a duration", TokenPosition{});
                        const auto duration = tokens.front().lexeme;
                        int64_t multiplier = 0;
                        if (duration.ends_with('s') || duration.ends_with('S')) multiplier = 1;
                        else if (duration.ends_with('m') || duration.ends_with('M')) multiplier = 60;
                        else if (duration.ends_with('h') || duration.ends_with('H')) multiplier = 60 * 60;
                        else if (duration.ends_with('d') || duration.ends_with('D')) multiplier = 24 * 60 * 60;
                        else throw ParseError("Unsupported window slice duration", TokenPosition{});
                        window_options.push_back({.name = "slice", .value = DurationNsLiteral{std::stoll(duration.substr(0, duration.size() - 1)) * multiplier * 1'000'000'000LL}});
                    }
                    else if (name == "pv_group" || name == "PV_GROUP")
                    {
                        try { window_options.push_back({.name = "pv_group", .value = static_cast<int64_t>(std::stoll(std::string(value)))}); }
                        catch (const std::exception&) { throw ParseError("Window pv_group option requires an integer", TokenPosition{}); }
                    }
                    else throw ParseError("Unknown window option: " + name, TokenPosition{});
                    if (comma == std::string_view::npos) break;
                    offset = comma + 1;
                }
            }
        }
        if (previous == "IN" && uppercase(child_sql).rfind("SELECT", 0) != 0)
        {
            search = end;
            continue;
        }
        const auto child = QueryParser::parse(child_sql);
        if (!std::holds_alternative<SelectStatement>(child)) throw ParseError("Subquery must contain SELECT", TokenPosition{});
        if (previous == "IN")
        {
            const auto marker = "in_subquery_" + std::to_string(derived_number++);
            in_subqueries.emplace(marker, std::make_shared<SelectStatement>(std::get<SelectStatement>(child)));
            if (!window_options.empty()) in_subquery_window_options.emplace(marker, std::move(window_options));
            rewritten.replace(search, end - search, "('" + marker + "')");
            search += marker.size() + 4;
            continue;
        }
        std::size_t alias_start = end;
        while (alias_start < rewritten.size() && std::isspace(static_cast<unsigned char>(rewritten[alias_start]))) ++alias_start;
        if (uppercase(std::string_view(rewritten).substr(alias_start, 3)) == "AS ")
        {
            alias_start += 3;
            while (alias_start < rewritten.size() && std::isspace(static_cast<unsigned char>(rewritten[alias_start]))) ++alias_start;
        }
        std::size_t alias_end = alias_start;
        while (alias_end < rewritten.size() && (std::isalnum(static_cast<unsigned char>(rewritten[alias_end])) || rewritten[alias_end] == '_')) ++alias_end;
        const auto marker = "derivedsubquery" + std::to_string(derived_number++);
        derived.emplace(marker, std::make_shared<SelectStatement>(std::get<SelectStatement>(child)));
        rewritten.replace(search, end - search, marker);
        search = alias_end - (end - search) + marker.size();
    }
    // Null predicates are local-filter-only. Rewrite them to otherwise
    // impossible string comparisons and restore their AST forms below.
    std::size_t null_search = 0;
    while (null_search < rewritten.size())
    {
        const auto upper_tail = uppercase(std::string_view(rewritten).substr(null_search));
        const auto null_relative = upper_tail.find(" IS NULL");
        const auto not_null_relative = upper_tail.find(" IS NOT NULL");
        const auto relative = null_relative == std::string::npos ? not_null_relative
            : not_null_relative == std::string::npos ? null_relative
                                                     : std::min(null_relative, not_null_relative);
        if (relative == std::string::npos) break;
        null_search += relative;
        const bool negated = uppercase(std::string_view(rewritten).substr(null_search)).starts_with(" IS NOT NULL");
        const auto marker = std::string(negated ? "__is_not_null_" : "__is_null_") + std::to_string(is_not_null.size());
        is_not_null.emplace(marker, negated);
        const auto length = negated ? std::string_view{" IS NOT NULL"}.size() : std::string_view{" IS NULL"}.size();
        rewritten.replace(null_search, length, " != '" + marker + "'");
        null_search += marker.size() + 6;
    }
    std::unordered_map<std::string, double> decimals;
    const auto decimal_rewritten = rewriteDecimalLiterals(rewritten, decimals);
    auto result = QueryParser(Lexer(decimal_rewritten).tokenize()).parse();
    if (!std::holds_alternative<SelectStatement>(result)) return result;
    auto& select = std::get<SelectStatement>(result);
    const auto restore = [&decimals, &typed_literals](LiteralValue& literal)
    {
        if (!std::holds_alternative<std::string>(literal)) return;
        const auto& text = std::get<std::string>(literal);
        if (const auto it = decimals.find(text); it != decimals.end()) literal = it->second;
        else if (const auto it = typed_literals.find(text); it != typed_literals.end()) literal = it->second;
    };
    const auto restore_expression = [&restore](const auto& self, ExpressionPtr& expression) -> void
    {
        if (!expression) return;
        if (auto* literal = std::get_if<LiteralValue>(&expression->value))
        {
            restore(*literal);
        }
        else if (auto* function = std::get_if<FunctionCall>(&expression->value))
        {
            for (auto& argument : function->arguments) self(self, argument);
        }
    };
    for (auto& item : select.select_items) restore_expression(restore_expression, item.expression);
    for (auto& order_by : select.order_by) restore_expression(restore_expression, order_by.expression);
    for (auto& predicate : select.predicates)
    {
        if (auto* equal = std::get_if<EqPredicate>(&predicate))
        {
            restore(equal->value);
            restore_expression(restore_expression, equal->expression);
        }
        else if (auto* in = std::get_if<InPredicate>(&predicate))
        {
            for (auto& value : in->values) restore(value);
            for (auto& expression : in->expressions) restore_expression(restore_expression, expression);
        }
        else if (auto* range = std::get_if<RangePredicate>(&predicate))
        {
            restore(range->lower);
            restore(range->upper);
            restore_expression(restore_expression, range->lower_expression);
            restore_expression(restore_expression, range->upper_expression);
        }
        else if (auto* op = std::get_if<OpPredicate>(&predicate))
        {
            restore(op->value);
            restore_expression(restore_expression, op->expression);
        }
    }
    if (!derived.empty() || !in_subqueries.empty() || !is_not_null.empty())
    {
        if (!std::holds_alternative<SelectStatement>(result)) return result;
        const auto attach = [&derived](TableRef& ref)
        {
            if (const auto it = derived.find(ref.table_name); it != derived.end()) ref.derived_query = it->second;
        };
        attach(select.from);
        for (auto& join : select.joins) attach(join.table);
        for (auto& predicate : select.predicates)
        {
            if (auto* in = std::get_if<InPredicate>(&predicate); in != nullptr && in->values.size() == 1 && std::holds_alternative<std::string>(in->values.front()))
            {
                const auto& marker = std::get<std::string>(in->values.front());
                if (const auto it = in_subqueries.find(marker); it != in_subqueries.end())
                {
                    in->values.clear();
                    in->subquery = it->second;
                    if (const auto options = in_subquery_window_options.find(marker); options != in_subquery_window_options.end())
                        in->window_options = options->second;
                }
            }
            else if (const auto* op = std::get_if<OpPredicate>(&predicate); op != nullptr && op->op == PredicateBinaryOp::NEQ && std::holds_alternative<std::string>(op->value) && is_not_null.contains(std::get<std::string>(op->value)))
            {
                predicate = is_not_null.at(std::get<std::string>(op->value))
                    ? WherePredicate{IsNotNullPredicate{.column = op->column}}
                    : WherePredicate{IsNullPredicate{.column = op->column}};
            }
        }
        return result;
    }
    return result;
}

mldp_pvxs_driver::query::QueryStatement mldp_pvxs_driver::query::parseQuery(const std::string_view sql)
{
    return QueryParser::parse(sql);
}
