name: BuildAndTes

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - main
  merge_group:
    branches:
      - main
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
  build_test_ubuntu:
    name: Build and test
    runs-on: ubuntu-latest
    container: docker:23.0.0-cli
    env:
      BUILD_TYPE: Debug
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      # - name: Install GitVersion
      #   uses: gittools/actions/gitversion/setup@v4.2.0
      #   with:
      #     versionSpec: '6.4.x'
      #     preferLatestVersion: true
      # - name: Determine Version
      #   id: gitversion
      #   uses: gittools/actions/gitversion/execute@v4.2.0
      #   with:
      #     useConfigFile: true
      # - name: Update version header
      #   run: |
      #     cat > include/version.h <<EOF
      #     #pragma once

      #     #define MLDP_PVXS_DRIVER_VERSION_MAJOR ${{ steps.gitversion.outputs.Major }}
      #     #define MLDP_PVXS_DRIVER_VERSION_MINOR ${{ steps.gitversion.outputs.Minor }}
      #     #define MLDP_PVXS_DRIVER_VERSION_PATCH ${{ steps.gitversion.outputs.Patch }}
      #     #define MLDP_PVXS_DRIVER_VERSION "${{ steps.gitversion.outputs.SemVer }}"
      #     EOF
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build dev image (cached)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: .devcontainer/Dockerfile
          tags: mldp-pvxs-driver-ci:latest
          cache-from: type=registry,ref=ghcr.io/slaclab/mldp-pvxs-driver:buildcache
          cache-to: type=registry,ref=ghcr.io/slaclab/mldp-pvxs-driver:buildcache,mode=max
          load: true
          build-args: |
            COMPILER=llvm
            PVXS_VERSION=1.4.1
      - name: Configure, build, test inside dev image
        id: build
        run: |
          docker compose -f docker-compose.yml -f docker-compose-test.yml --profile prebuilt up --abort-on-container-exit --exit-code-from ci-prebuilt ci-prebuilt
