name: BuildAndTes

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - main
  merge_group:
    branches:
      - main
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
  build_test_ubuntu:
    name: Build Ubuntu
    runs-on: ubuntu-latest
    container: docker:23.0.0-cli
    env:
      BUILD_TYPE: Debug
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      # - name: Install GitVersion
      #   uses: gittools/actions/gitversion/setup@v4.2.0
      #   with:
      #     versionSpec: '6.4.x'
      #     preferLatestVersion: true
      # - name: Determine Version
      #   id: gitversion
      #   uses: gittools/actions/gitversion/execute@v4.2.0
      #   with:
      #     useConfigFile: true
      # - name: Update version header
      #   run: |
      #     cat > include/version.h <<EOF
      #     #pragma once

      #     #define MLDP_PVXS_DRIVER_VERSION_MAJOR ${{ steps.gitversion.outputs.Major }}
      #     #define MLDP_PVXS_DRIVER_VERSION_MINOR ${{ steps.gitversion.outputs.Minor }}
      #     #define MLDP_PVXS_DRIVER_VERSION_PATCH ${{ steps.gitversion.outputs.Patch }}
      #     #define MLDP_PVXS_DRIVER_VERSION "${{ steps.gitversion.outputs.SemVer }}"
      #     EOF
      - name: Build dev image
        run: docker compose -f docker-compose-test.yml build ci
      - run: git config --global --add safe.directory '*'
      - name: Configure, build, test inside dev image
        id: build
        run: |
          docker compose -f docker-compose.yml -f docker-compose-test.yml up --abort-on-container-exit --exit-code-from ci ci
